### GET Request

GET http://localhost:3000/players/

### POST Request

POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}


### GET Request

GET http://localhost:3000/players/1/

### PUT Request
PUT http://localhost:3000/players/5/
Content-Type: application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}


### DELETE Request
DELETE http://localhost:3000/players/7/